# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iwGDoSvOtMFWMtIjCCsZiQNwdRjn6mQQ
"""

import json,random,PyPDF2 as pdf
from datetime import datetime as dt
from flask import Flask, request, jsonify
from flask_cors import CORS
from difflib import get_close_matches

app = Flask(_name_)
CORS(app)

def loader(file_path: str) -> dict:
    with open(file_path, 'r') as file:
        data: dict = json.load(file)
    return data

def bestmatch(user_question: str, questions: list[list[str]]) -> str | None:
    all_variations = [variation for sublist in questions for variation in sublist]
    matches: list = get_close_matches(user_question, all_variations, n=1, cutoff=0.6)
    return matches[0] if matches else None

def getans(matched_question: str, knowledge_base: dict) -> str | None:
    for q in knowledge_base["questions"]:
        if matched_question in q["question"]:
            answer = q["answer"]
            if isinstance(answer, list):
                return random.choice(answer)
            return answer
    return "Sorry, I don't understand that."

@app.route('/chat', methods=["POST"])
def chat():
    user_message = request.json.get('message')
    if not user_message:
        return jsonify({'answer': "Please send a valid message."}), 400

    daata = loader('data.json')

    best_match = bestmatch(user_message, [q['question'] for q in daata['questions']])

    if best_match:
        answer = getans(best_match, daata)

    elif user_message.lower() in ['time', 'whats the time now','what is time']:
        print(f"Bot: its {dt.now().time()}")

    elif user_message.lower() in ['today', 'date']:
        print(f"Bot: today is {dt.now().strftime("%A")} {dt.now().date()}")

    elif user_message.lower() in ["convert","convert to text file","extract"]:
        ftype=input('enter file type:')
        if ftype in ["txt","text"]:
                loc=input("enter file path[eg./file/path/xyz.type]")
                with open(loc) as file:
                    cont=file.read()
                    print(cont)

        elif ftype in ['pdf']:
            try:
                loc = input("Enter file path [e.g., /file/path/xyz.type]: ").strip().strip("'").strip('"')
                with open(loc, 'rb') as file:
                    print("File opened successfully!")
                    pdf_reader = pdf.PdfReader(file)
                    for page_num in range(len(pdf_reader.pages)):
                            page = pdf_reader.pages[page_num]
                            text = page.extract_text()
                            if text:
                                print(f"Page {page_num + 1}:")
                                print(text)
                    else:
                          print(f"Page {page_num + 1}: No extractable text.")
            except FileNotFoundError:
                     print(f"Error: The file at '{loc}' was not found. Please check the path and try again.")

    else:
        answer = "That's beyond my knowledge. Can you please ask me something else?"

    return jsonify({'answer': answer})

if _name_ == "_main_":
    app.run(debug=True)